name: Docs
on: [push]

jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build
      - run: npm run doc
        env:
          OCTOKITBOT_PAT: ${{ secrets.OCTOKITBOT_PAT }}
